language: node.js
node_js:
  - 14.6.0
cache: yarn

install:
  - cd backend
  - yarn install
  - cd ..
  - cd frontend
  - yarn install

script:
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
